
export const COURSE_REQUEST="COURSE_REQUEST"
export const COURSE_SUCCESS="COURSE_SUCCESS"  
export const COURSE_SUCCESS_INST ="COURSE_SUCCESS_INST "  
export const COURSE_FAILUER="COURSE_FAILUER"  
export const COURSE_SUCCESS_ASSIGN="COURSE_SUCCESS_ASSIGN" 
